name: go_pass

volumes:

  go_pass_postgres_volume:
    name: go_pass_postgres_volume

networks:

  go_pass_network:
    name: go_pass_network
    driver: bridge

services:

  postgres:

    hostname: postgres
    container_name: go_pass_postgres
    image: postgres:14.7-alpine
    restart: always
    volumes:
      - go_pass_postgres_volume:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
    networks:
      - go_pass_network

  backend:

    container_name: go_pass_backend
    build: .
    image: go_pass_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:${API_PORT}
    tty: true
    environment:
      - TZ=${TZ}
    networks:
      - go_pass_network